# Generated by Django 5.2.2 on 2025-06-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_songs', to='songs.album'),
        ),
    ]
