# Generated by Django 5.2.2 on 2025-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_album_slug_author_slug_song_slug_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
